# Generated by Django 3.1 on 2020-08-10 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AddField(
            model_name='device',
            name='application_eui',
            field=models.CharField(max_length=64, null=True, verbose_name='EUI da Aplicação'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='data.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Medição',
                'verbose_name_plural': 'Medições',
            },
        ),
    ]
