# Generated by Django 3.1 on 2020-08-10 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200810_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='humidity',
            field=models.FloatField(null=True, verbose_name='umidade'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(null=True, verbose_name='temperatura'),
        ),
    ]
