# Generated by Django 3.1 on 2020-08-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200810_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='payload',
            field=models.JSONField(blank=True, null=True, verbose_name='pacote de dados'),
        ),
    ]
