# Generated by Django 3.1 on 2020-08-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200810_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='payload',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='pacote de dados'),
        ),
    ]
