# Generated by Django 3.1 on 2020-08-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200811_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='mold_growth',
            field=models.FloatField(blank=True, null=True, verbose_name='crescimento esperado de mofo'),
        ),
    ]
